modLoader="javafml"
loaderVersion="[31,)"
license="All rights reserved"
[[mods]]
modId="burnlog2char"
version="${file.jarVersion}"
displayName="Burn Logs to Charcoal"
description='''
Burn any Logs to Charcoal
'''
[[dependencies.burnlog2char]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.57,)"
    ordering="NONE"
    side="BOTH"