modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="burnlog2char"
version="${file.jarVersion}"
displayName="Burn Logs to Charcoal"
description='''
Burn any Logs to Charcoal
'''
[[dependencies.burnlog2char]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,)"
    ordering="NONE"
    side="BOTH"